Repository CAU-CSE-24-02-Capstone-Design/BackEnd, pull requests merged in 2024-11, with the labels that each got.

#19 feat/ 유저가 그 달에 실행한 calendar 체크
  src/main/java/Team02/BackEnd/config/SwaggerConfig.java
  src/main/java/Team02/BackEnd/controller/UserController.java
  src/main/java/Team02/BackEnd/dto/UserResponseDto.java
  src/main/java/Team02/BackEnd/jwt/service/JwtService.java
  src/main/java/Team02/BackEnd/repository/AnswerRepository.java
  src/main/java/Team02/BackEnd/service/UserService.java
  src/main/resources/data.sql
Labels: enhancement

#23 fix: feedback response 받아서 feedback update
  src/main/java/Team02/BackEnd/domain/Feedback.java
  src/main/java/Team02/BackEnd/service/FeedbackService.java
Labels: bug

#24 fix(Insight): varchar -> Text로 변경
  build.gradle
  src/main/java/Team02/BackEnd/BackEndApplication.java
  src/main/java/Team02/BackEnd/apiPayload/code/status/SuccessStatus.java
  src/main/java/Team02/BackEnd/config/JpaAuditingConfiguration.java
  src/main/java/Team02/BackEnd/controller/AnswerController.java
  src/main/java/Team02/BackEnd/controller/FeedbackController.java
  src/main/java/Team02/BackEnd/controller/SelfFeedbackController.java
  src/main/java/Team02/BackEnd/controller/UserController.java
  src/main/java/Team02/BackEnd/converter/AnswerConverter.java
  src/main/java/Team02/BackEnd/converter/SelfFeedbackConverter.java
  src/main/java/Team02/BackEnd/domain/Answer.java
  src/main/java/Team02/BackEnd/domain/Feedback.java
  src/main/java/Team02/BackEnd/domain/Insight.java
  src/main/java/Team02/BackEnd/domain/SelfFeedback.java
  src/main/java/Team02/BackEnd/domain/Statistics.java
  src/main/java/Team02/BackEnd/dto/AnswerResponseDto.java
  src/main/java/Team02/BackEnd/dto/SelfFeedbackRequestDto.java
  src/main/java/Team02/BackEnd/dto/SelfFeedbackResponseDto.java
  src/main/java/Team02/BackEnd/repository/AnswerRepository.java
  src/main/java/Team02/BackEnd/repository/FeedbackRepository.java
  src/main/java/Team02/BackEnd/repository/QuestionRepository.java
  src/main/java/Team02/BackEnd/repository/SelfFeedbackRepository.java
  src/main/java/Team02/BackEnd/repository/UserRepository.java
  src/main/java/Team02/BackEnd/service/AnswerService.java
  src/main/java/Team02/BackEnd/service/FeedbackService.java
  src/main/java/Team02/BackEnd/service/SelfFeedbackService.java
  src/main/java/Team02/BackEnd/service/UserService.java
  src/main/resources/data.sql
  src/test/java/Team02/BackEnd/controller/FeedbackControllerTest.java
  src/test/java/Team02/BackEnd/repository/AnswerRepositoryTest.java
  src/test/java/Team02/BackEnd/repository/FeedbackRepositoryTest.java
  src/test/java/Team02/BackEnd/repository/InsightRepositoryTest.java
  src/test/java/Team02/BackEnd/repository/QuestionRepositoryTest.java
  src/test/java/Team02/BackEnd/repository/SelfFeedbackRepositoryTest.java
  src/test/java/Team02/BackEnd/repository/UserRepositoryTest.java
  src/test/resources/application-test.yml
Labels: bug

#26 fix(AnswerController): 평가를 answer에 저장하기
  src/main/java/Team02/BackEnd/apiPayload/code/status/SuccessStatus.java
  src/main/java/Team02/BackEnd/controller/AnswerController.java
  src/main/java/Team02/BackEnd/controller/SelfFeedbackController.java
  src/main/java/Team02/BackEnd/converter/AnswerConverter.java
  src/main/java/Team02/BackEnd/converter/SelfFeedbackConverter.java
  src/main/java/Team02/BackEnd/domain/Answer.java
  src/main/java/Team02/BackEnd/domain/SelfFeedback.java
  src/main/java/Team02/BackEnd/dto/AnswerRequestDto.java
  src/main/java/Team02/BackEnd/dto/AnswerResponseDto.java
  src/main/java/Team02/BackEnd/dto/SelfFeedbackRequestDto.java
  src/main/java/Team02/BackEnd/dto/SelfFeedbackResponseDto.java
  src/main/java/Team02/BackEnd/oauth/service/OauthService.java
  src/main/java/Team02/BackEnd/service/AnswerService.java
  src/main/java/Team02/BackEnd/service/FeedbackService.java
  src/main/java/Team02/BackEnd/service/InsightService.java
  src/main/java/Team02/BackEnd/service/QuestionService.java
  src/main/java/Team02/BackEnd/service/ReissueService.java
  src/main/java/Team02/BackEnd/service/SelfFeedbackService.java
  src/main/java/Team02/BackEnd/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/Team02/BackEnd/BackEndApplicationTests.java
  src/test/java/Team02/BackEnd/repository/AnswerRepositoryTest.java
  src/test/java/Team02/BackEnd/repository/FeedbackRepositoryTest.java
  src/test/java/Team02/BackEnd/repository/InsightRepositoryTest.java
  src/test/java/Team02/BackEnd/repository/SelfFeedbackRepositoryTest.java
Labels: enhancement

#27 feat(StatisticsService): 통계 로직 작성 완료
  src/main/java/Team02/BackEnd/apiPayload/code/status/ErrorStatus.java
  src/main/java/Team02/BackEnd/apiPayload/exception/handler/StatisticsHandler.java
  src/main/java/Team02/BackEnd/controller/AnswerController.java
  src/main/java/Team02/BackEnd/controller/FeedbackController.java
  src/main/java/Team02/BackEnd/controller/InsightController.java
  src/main/java/Team02/BackEnd/controller/QuestionController.java
  src/main/java/Team02/BackEnd/controller/RecordController.java
  src/main/java/Team02/BackEnd/controller/SelfFeedbackController.java
  src/main/java/Team02/BackEnd/controller/StatisticsController.java
  src/main/java/Team02/BackEnd/converter/AnswerConverter.java
  src/main/java/Team02/BackEnd/converter/FeedbackConverter.java
  src/main/java/Team02/BackEnd/converter/InsightConverter.java
  src/main/java/Team02/BackEnd/converter/QuestionConverter.java
  src/main/java/Team02/BackEnd/converter/SelfFeedbackConverter.java
  src/main/java/Team02/BackEnd/converter/StatisticsConverter.java
  src/main/java/Team02/BackEnd/domain/Feedback.java
  src/main/java/Team02/BackEnd/domain/Statistics.java
  src/main/java/Team02/BackEnd/dto/answerDto/AnswerRequestDto.java
  src/main/java/Team02/BackEnd/dto/answerDto/AnswerResponseDto.java
  src/main/java/Team02/BackEnd/dto/feedbackDto/FeedbackRequestDto.java
  src/main/java/Team02/BackEnd/dto/feedbackDto/FeedbackResponseDto.java
  src/main/java/Team02/BackEnd/dto/insightDto/InsightRequestDto.java
  src/main/java/Team02/BackEnd/dto/insightDto/InsightResponseDto.java
  src/main/java/Team02/BackEnd/dto/questionDto/QuestionResponseDto.java
  src/main/java/Team02/BackEnd/dto/recordDto/RecordRequestDto.java
  src/main/java/Team02/BackEnd/dto/selfFeedbackDto/SelfFeedbackRequestDto.java
  src/main/java/Team02/BackEnd/dto/selfFeedbackDto/SelfFeedbackResponseDto.java
  src/main/java/Team02/BackEnd/dto/statisticsDto/StatisticsRequestDto.java
  src/main/java/Team02/BackEnd/dto/statisticsDto/StatisticsResponseDto.java
  src/main/java/Team02/BackEnd/dto/userDto/UserRequestDto.java
  src/main/java/Team02/BackEnd/dto/userDto/UserResponseDto.java
  src/main/java/Team02/BackEnd/repository/StatisticsRepository.java
  src/main/java/Team02/BackEnd/service/FeedbackService.java
  src/main/java/Team02/BackEnd/service/SelfFeedbackService.java
  src/main/java/Team02/BackEnd/service/StatisticsService.java
  src/main/java/Team02/BackEnd/service/UserService.java
Labels: enhancement

#28 fix(JWT): filter 로깅 삭제
  src/main/java/Team02/BackEnd/controller/StatisticsController.java
  src/main/java/Team02/BackEnd/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/Team02/BackEnd/jwt/service/JwtService.java
  src/main/java/Team02/BackEnd/service/StatisticsService.java
  src/test/java/Team02/BackEnd/controller/AnswerControllerTest.java
  src/test/java/Team02/BackEnd/repository/StastisticsRepositoryTest.java
Labels: documentation
